# Generated by Django 2.2 on 2019-05-13 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(blank=True, choices=[('Futbol', 'Futbol'), ('Finans', 'Finans'), ('Teknoloji', 'Teknoloji')], max_length=255, null=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('body', models.TextField()),
                ('allow_comments', models.BooleanField(default=True, verbose_name='allow comments')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(default='Blog', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Futbol', 'Futbol'), ('Finans', 'Finans'), ('Teknoloji', 'Teknoloji')], max_length=255, null=True)),
                ('document', models.FileField(upload_to='documents/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dataset_title', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_5_row', models.CharField(blank=True, max_length=2000, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(default='Veriseti', max_length=255)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('job_talents', models.CharField(blank=True, max_length=255, null=True)),
                ('uni', models.CharField(blank=True, max_length=255, null=True)),
                ('rustudent', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('approve', models.BooleanField(default=False, verbose_name='approve')),
                ('apply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
