# Generated by Django 2.2 on 2019-05-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_qa_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
