# Generated by Django 2.2 on 2019-05-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_qanswer_compare_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qanswer',
            name='compare_id',
            field=models.CharField(max_length=250),
        ),
    ]
