# Generated by Django 2.2 on 2019-05-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190516_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': ''},
        ),
    ]
