# Generated by Django 2.2 on 2019-05-16 12:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_auto_20190516_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='CustomProfile',
        ),
    ]
