# Generated by Django 2.2 on 2019-05-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190516_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customprofile',
            name='birth_date',
        ),
    ]
