# Generated by Django 2.2 on 2019-05-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190517_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='avatar',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
