# Generated by Django 2.2.1 on 2019-05-17 22:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20190518_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 17, 22, 37, 40, 758692, tzinfo=utc)),
        ),
    ]
