# Generated by Django 2.2.1 on 2019-05-22 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20190518_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qanswer',
            name='id',
        ),
        migrations.AddField(
            model_name='qanswer',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
