# Generated by Django 2.2.1 on 2019-05-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20190522_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qanswer',
            old_name='unique_id',
            new_name='unique_id2',
        ),
    ]
