# Generated by Django 2.2.1 on 2019-05-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20190523_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='edit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
