# Generated by Django 2.2.1 on 2019-05-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20190524_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='edit_time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
