# Generated by Django 2.2.1 on 2019-05-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20190524_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qanswer',
            name='edit_time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
