# Generated by Django 2.2.1 on 2019-05-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20190524_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='edit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qanswer',
            name='edit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
